//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCXC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsientoContable
    {
        public string description { get; set; }
        public Nullable<int> AccountSeat { get; set; }
        public string account { get; set; }
        public string movementType { get; set; }
        public string entryDate { get; set; }
        public string seatAmount { get; set; }
        public string status { get; set; }
        public int idClient { get; set; }
        public Nullable<int> idAuxiliarSystem { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
