//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCXC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsientosContable
    {
        public int ID { get; set; }
        public string Description { get; set; }
        public int IdAuxiliarSystem { get; set; }
        public string MovementType { get; set; }
        public System.DateTime EntryDate { get; set; }
        public bool Status { get; set; }
        public int idClient { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
