 //------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCXC.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;
    using System.ComponentModel.DataAnnotations;

    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.Transaccions = new HashSet<Transaccion>();
        }
    
        public int cliente_id { get; set; }
        [Required]
        [StringLength(50)]
        [RegularExpression(@"([a-zA-Z]+( [a-zA-Z]+)+)", ErrorMessage = "Use letras solamente por favor.")]
        public string nombre { get; set; }
        [Required]
        [StringLength(11, ErrorMessage = "La cedula introducida es muy larga.")]
        [Range(0, 9999999999999999, ErrorMessage = "No se aceptan números negativos.")]
        [RegularExpression("([1-9][0-9]*)", ErrorMessage = "Solo se aceptan números.")]
        public string cedula { get; set; }
        [Required]
        [Range(0, 9999999999999999.99, ErrorMessage = "Solo se aceptan 2 decimales después del punto.")]
        [RegularExpression(@"^\d+.?\d{0,2}$", ErrorMessage = "Solo se aceptan números positivos con formato 999.99.")]
        public decimal limiteCredito { get; set; }
        public string estado { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaccion> Transaccions { get; set; }

    }
}
