//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCXC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TipoDoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TipoDoc()
        {
            this.Transaccions = new HashSet<Transaccion>();
        }
    
        public int tipoDoc_id { get; set; }
        [Required]
        [StringLength(50)]
        public string descripcion { get; set; }
        [Required]
        [Range(0, int.MaxValue, ErrorMessage = "No se aceptan números negativos.")]
        [RegularExpression("([1-9][0-9]*)", ErrorMessage = "Solo se aceptan números.")]
        public Nullable<int> cuentaContable { get; set; }
        public string estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaccion> Transaccions { get; set; }
    }
}
