//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCXC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaccion
    {
        public int transaccion_id { get; set; }
        public string tipoMovimiento { get; set; }
        public Nullable<int> tipoDoc_id { get; set; }
        public int numDoc { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> cliente_id { get; set; }
        public Nullable<decimal> monto { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual TipoDoc TipoDoc { get; set; }
    }
}
